### ISSUE TITLE
generic model

### ISSUE THREAD

**Issue by Mir-SA** [Real-Dev-Squad/website-data-models#12]
### How model can look like
```
Tags: {
	id: String,
        type: String,
	date: Timestamp,
	...tagData
}
UserTags: {
	userid: String,
	tagid: String,
}
```
	
- User can create a tag with any type. for e.g SKILL, TASK, GOAL, ANY 
- We can add data for that tag  in `Tags` model by adding in a `type` field & fetch them based on their type.
- We can refer `userid` in `UserTags` to fetch all tags by their id.
- **Caveat: Its quite likely that we'll end up doing a lot of read queries because of that second referential collection**
---
### Some possible ways to request & query the API & DB

**1. To get all tags for a user** 
  - Endpoint = `/tags/:userid`
  - Query = `userTagsModel.where('userid', ==  , userid).get()`
  - Once all docs are returned from userTagsModel we'll have to do query for *each tagid*

**2. To get tags of a *type***
  - Endpoint = `/tags/:type`
  - Query = `tagsModel.where('type', ==  , type).get()`
  - This is fairly simple

**3. To get tags of a type for a user**
  - Endpoint = `/tags?id={userid}&type={type}`
  - Queries =  `	   userTagsModel.where('userid', ==  , userid).get() `
  - Once docs are returned  we'll have to query for _each tagid_ & _check for their type_

----
**Data Aggregation**
- Aggregate data with cloud functions. We can put a DB trigger and add user-id to tag model whenever a new doc is added to userTags model
- Or we can simply add user-id to tag model while posting data to it
- With both methods we will be performing *denormalization* or data-duplication. This is fairly common in NoSQL land and can help reduce multiple queries

**Comment by vinayak-trivedi** [comment]
I've one question @Mir-SA you have mentioned a tags model here which can be used as a generic model I guess, let me know if I am wrong, I am talking about [this](https://github.com/Real-Dev-Squad/website-data-models/issues/9)

**Comment by Mir-SA** [comment]
No. Not the tags model. 
This is for userTags model. 
We've to make userTags a more generic model for other user relattions

**Comment by vinayak-trivedi** [comment]
okay got it

**Comment by vinayak-trivedi** [comment]
### Requirements for tags in task leveling feature

- we want to add a particular skill tag to the user when they change the status of that particular task to `merged`
- For now, as per the suggestion by @ankushdharkar there will be a task logs screen in the dashboard site which will allow the `superuser` to see all the logs and manually add a tag to a particular user.

### Questions
- we need to store the level of the skill that the particular user has, and update it when a user completes a particular number of tasks of that particular skill, so I've two questions: 
  - How are we planning to store the number of tasks a particular user has done of a particular skill and level?
  - how are we storing the skill levels of every user?

**Comment by DashDeipayan** [comment]
**Data Models:**
- Model =
	```
		Tags: {
			id: String,
                   type: String,
			name: String,
			createdBy: String,
			reason: String,
			date: Timestamp,
		}
		ItemTags: {
			itemid: String,
			tagid: String,
                        itemType: String
		}
	``` 
- UserID & TagID will be used as FK to create a link between Tag Model & User Model
- Each document in `UserTags` will contain the skills of users by a reference to their TagID & UserID
- This collection `UserTags` can also be used to store user contextual data.

### Requirements
1. Create Skill Data
2. Fetch all skills in the collection
3. Fetch users with a certain skill
4. Fetch skills of a certain user

**Comment by vinayak-trivedi** [comment]
> 

I have one question about this, do we really need to create separate itemTag doc for tasks, a particular task that has a tag of react, doesn't need other tags like ember, so we can directly put the id of that particular tag to that task object only

one more question that I have is that the tags are not going to have id right? we can use the doc id as their id. Let me know if I am getting it wrong

**Comment by DashDeipayan** [comment]
ItemTags can have every possible items and also multiple tags of the same item. For tasks, a task may not have `react` and `ember` tags at the same time but can have `react` and `front-end` tags, or `react` and `redux` tags.
```
{
        itemid: some_react_taskid,
        tagid: some_id_feature_react
        itemType: TASK
        levelid: some_id_level_4
    },
{
        itemid: some_react_taskid,
        tagid: some_id_feature_redux
        itemType: TASK
        levelid: some_id_level_4
    }
```

**Comment by vinayak-trivedi** [comment]
> ItemTags can have every possible items and also multiple tags of the same item. For tasks, a task may not have `react` and `ember` tags at the same time but can have `react` and `front-end` tags, or `react` and `redux` tags.
> 
> ```
> {
>         itemid: some_react_taskid,
>         tagid: some_id_feature_react
>         itemType: TASK
>         levelid: some_id_level_4
>     },
> {
>         itemid: some_react_taskid,
>         tagid: some_id_feature_redux
>         itemType: TASK
>         levelid: some_id_level_4
>     }
> ```
yeah makes sense

**Comment by prakashchoudhary07** [comment]
Closing this in favour of skill-tree
