### ISSUE TITLE
Update  `users statuses` data model to handle `future status` along with `current status` 

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/website-data-models#17]
Presently in the data model for `users statuses` collection, we store `current status`. Now if the users mark themselves as `OOO` for a future date then it overwrites the object in `current status` and we lose the `current status` of the users. To solve this issue we have come up with an idea to store `future status` along with `current status` in the document as well. The `future status` will work as follows: 

- [x] If the users are currently `active/idle` and they mark themselves as `OOO` for a future date then the new object with the same fields as `current status` will be created and stored in `future status`. once when the future date arrives the values in the `current status` and `future status` will be swapped with the dates adjusted accordingly so that once the users are back in office they have the same status that they had prior to leaving office.
- [x]  If the users are currently `active/idle` and they mark themselves as `OOO` for a future date then the new object will be created and stored in `future status`. Once the future dates start and their status changes to `OOO` and before completing their `OOO` tenure they mark themselves as `IDLE / ACTIVE` we will set the current status as `IDLE / ACTIVE` and remove the `future status` which was waiting to be swapped. 
- [x]  If the users are currently `active/idle` and they mark themselves as `OOO` for a future date and later before their `OOO` dates arrive they again mark themselves `OOO` the latest one will be considered it will overwrite the previously written object in the `future status`.
- [x] if the users have marked themselves as `OOO` for a future date and they change their current status as well with `OOO` then it will remove the old `OOO` from the `future status`. 

We won't be giving the date selection field for `ACTIVE`& `IDLE` anymore to the Users. It will be considered by default from the date on which the users mark themselves as `ACTIVE` or `IDLE`. This is done in order that someone doesn't mark themselves as `IDLE` from a past date and show up in the queue of `IDLE` Users. Date selection would be exclusive to `OOO` now. 

Along with this, we need to create a button in the dashboard site that when triggered by the super user goes through all the user statuses and sees if the dates stored in future statuses have arrived and if arrived, does the update in `current status`.  Ideally, this should be automated later and should be triggered every day once.

That was all the edge cases I can come up with. Please let me know if you can think of anything else which has been missed.

**Comment by RitikJaiswal75** [comment]
@heyrandhir can you elaborate on 4th checkpoint, I could not understand it.

**Comment by heyrandhir** [comment]
> @heyrandhir can you elaborate on 4th checkpoint, I could not understand it.

Yes sure. If the Users have marked themselves `OOO` for a future date and now again they mark themselves as `OOO` from today then the `OOO` which they had marked earlier will be invalid. The Rule of thumb here is the latest `OOO` will be considered the single source of truth. 

Let me know if its still unclear @RitikJaiswal75

**Comment by RitikJaiswal75** [comment]
To other readers, (providing some context) this feature is not just for `ooo` it is going to be similar for all other statuses.
For active status, you can only select the date you mark yourself active, else you are either `ooo` or `idle`
For idle status, you can only select the present date. No future or past dates will be allowed.
For ooo status, you can only select the future dates. No past dates are allowed.

**Comment by heyrandhir** [comment]
> To other readers, (providing some context) this feature is not just for `ooo` it is going to be similar for all other statuses. For active status, you can only select the date you mark yourself active, else you are either `ooo` or `idle` For idle status, you can only select the present date. No future or past dates will be allowed. For ooo status, you can only select the future dates. No past dates are allowed.

@RitikJaiswal75 , as @ankushdharkar suggested we won't be giving the date selection field in `ACTIVE`& `IDLE`. It will be considered from the date on which they mark themselves as `ACTIVE` or `IDLE`. This is done in order that someone doesn't mark themselves as `IDLE` from a past date and come up in the queue. date selection would be exclusive to `OOO` only now.

**Comment by heyrandhir** [comment]
This is a documentation Ticket hence closing it.
