### ISSUE TITLE
Skills data modelling

### ISSUE THREAD

**Issue by Mir-SA** [Real-Dev-Squad/website-data-models#9]
**Data Models:**
- Model =
	```
		Tags: {
			id: String,
                   type: String,
			name: String,
			createdBy: String,
			reason: String,
			date: Timestamp,
		}
		UserTags: {
			userid: String,
			tagid: String,
		}
	``` 
- UserID & TagID will be used as FK to create a link between Tag Model & User Model
- Each document in `UserTags` will contain the skills of users by a reference to their TagID & UserID
- This collection `UserTags` can also be used to store user contextual data.

### Requirements
1. Create Skill Data
2. Fetch all skills in the collection
3. Fetch users with a certain skill
4. Fetch skills of a certain user

**Comment by rajakvk** [comment]
@Mir-SA Please tag 'feature owner' and 'Application owner' so that they will share their opinion.

**Comment by pallabez** [comment]
What is 

```
 		tag1id: String,
 		tag2id: String,
 		date: Timestamp,
```

**Comment by pallabez** [comment]
Can we have this issue ticket synced with the PR?

**Comment by Mir-SA** [comment]
> What is
> 
> ```
>  		tag1id: String,
>  		tag2id: String,
>  		date: Timestamp,
> ```

i'm thinking of using that model to store IDs of all usertags(skills)

**Comment by pallabez** [comment]
Shouldn't it be an array then? 

tag: [tag1, tag2, ...];

**Comment by Mir-SA** [comment]
> Shouldn't it be an array then?
> 
> tag: [tag1, tag2, ...];

it can be but [document size](https://firebase.google.com/docs/firestore/quotas#collections_documents_and_fields) is limited to 1MB so if array grows quickly next write to doc will fail
initially i had taken that approach but ankush said not to

**Comment by pallabez** [comment]
It shouldn't unless you have 13k tag for that user considering it takes 80bytes for the tagID. 

Also, making 
```
tag1id: String,
tag2id: String,
``` 
won't make it any difference as the space consumption is same. 

But yeah, having object is prefered over array. I would suggest 
```
{
  userId: String,
  tags: {
    tag1id: Boolean,
    tag2id: Boolean, 
    ...
  } 
}
```

**Comment by Mir-SA** [comment]
> It shouldn't unless you have 13k tag for that user only considering it takes 80bytes for the tagID.

agree. i had pointed that out in previous pr  https://github.com/Real-Dev-Squad/website-data-models/pull/7#discussion_r938610939 and had some array-based & collection based approach but we eliminated all array appraoches. check previous edit in doc https://github.com/Real-Dev-Squad/website-data-models/issues/9#issue-1367273032

> But yeah, having object is prefered over array. I would suggest

maps are just as inefficient with space as array :/
point is to make data as granular as possible

**Comment by vinayak-trivedi** [comment]
1. How are we storing the levels of a particular skill that a user has? My suggestion is to add the levels in the doc in the userSKill collection. so it will be something like this: 
```
{
  userId: <userId>
  tagId: <tagId>
  tagLevel: <anything between 1-5>
}
```
then we can update the level of that particular tag here only and we do need to create multiple tags for different skill levels

2. How are we storing how many tasks a user has completed of a particular skill, which would be required to update a particular skill

**Comment by Mir-SA** [comment]
> 1. How are we storing the levels of a particular skill that a user has? My suggestion is to add the levels in the doc in the userSKill collection. so it will be something like this:
> 
> ```
> {
>   userId: <userId>
>   tagId: <tagId>
>   tagLevel: <anything between 1-5>
> }
> ```
> 
> then we can update the level of that particular tag here only and we do need to create multiple tags for different skill levels
> 
> 2. How are we storing how many tasks a user has completed of a particular skill, which would be required to update a particular skill

I think it would be better to store Skill Level, Tasks completed  & any metadata about Skills in Tags collection since it **particularly for diff type of Tags** whereas UserTags is **for tags related to user** & it is only there to create link between user & their Tags

**Comment by prakashchoudhary07** [comment]
Closing this in favor of the skill-tree feature
